import { Movie } from '@models';
import { TV } from 'src/models/tv';

export const nowPlayingList: Movie[] = [
  {
    adult: false,
    backdrop_path: '/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg',
    genre_ids: [878, 28],
    id: 580489,
    original_language: 'en',
    original_title: 'Venom: Let There Be Carnage',
    overview:
      'Siêu bom tấn #VENOM: LET THERE BE CARNAGE vừa bất ngờ tung đoạn trailer mãn nhãn, hứa hẹn trận chiến khốc liệt nhất giữa Venom và kẻ thù truyền kiếp, Carnage. Phim sẽ khởi chiếu DUY NHẤT TẠI RẠP vào ngày 24.09.2021 sắp tới. Cùng đón chờ!!',
    popularity: 9295.845,
    poster_path: '/489LD1LL2zQxFLbU6o5oslBhvwQ.jpg',
    release_date: '2021-09-30',
    title: 'Venom: Đối Mặt Tử Thù',
    video: false,
    vote_average: 7.2,
    vote_count: 627,
  },
  {
    adult: false,
    backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: 'en',
    original_title: 'Free Guy',
    overview:
      'Guy - Nhân viên giao dịch ngân hàng, phát hiện anh ấy thực chất là người chơi nền trong trò chơi điện tử thế giới mở. Guy quyết định trở thành người anh hùng và viết lại câu chuyện của chính mình. Giờ đây, trong một thế giới không còn giới hạn, anh ấy quyết định trở thành người giải cứu thế giới, theo cách của chính mình.',
    popularity: 4249.292,
    poster_path: '/kvTTnQ8C4RF0bZUAoYPD913NQx4.jpg',
    release_date: '2021-08-11',
    title: 'Giải Cứu Guy',
    video: false,
    vote_average: 7.8,
    vote_count: 2684,
  },
  {
    adult: false,
    backdrop_path: '/kTOheVmqSBDIRGrQLv2SiSc89os.jpg',
    genre_ids: [16, 35, 10751],
    id: 639721,
    original_language: 'en',
    original_title: 'The Addams Family 2',
    overview:
      'Sự trở lại của The Addams Family 2 vào năm 2021 sẽ mang tới những điều “dị thường” không thể ngờ tới. Chỉ vừa kịp tuyên bố điều này, chú béo Fester đã ăn ngay phải một cú chơi khăm từ người em họ lông lá Itt. Rủ Itt đi câu cá nhưng lại câu phải đúng thuốc nổ. Cháy hết quần áo, cô cháu gái Wednesday đã “giúp khéo” chú mình bằng cách phun mực đen lên người. Không cần nhiều dẫn giải, khán giả có thể nhận ra giọng lồng tiếng quen thuộc của nữ diễn Chloë Grace Moretz trong vai cô con gái lớn Wednesday “khó ở” của nhà Addams.',
    popularity: 2290.454,
    poster_path: '/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg',
    release_date: '2021-10-01',
    title: 'Gia Đình Addams 2',
    video: false,
    vote_average: 7.6,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: '/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg',
    genre_ids: [28, 12],
    id: 568620,
    original_language: 'en',
    original_title: 'Snake Eyes: G.I. Joe Origins',
    overview:
      'Snake Eyes: G.I. Joe Origins theo chân Snake Eyes - một chiến binh cô độc, ngoan cường bất ngờ được kết nạp vào gia tộc Arashikage sau khi cứu mạng người thừa kế của họ. Khi đến Nhật Bản, Arashikage dạy Snake Eyes những chiêu thức cơ bản của một chiến binh ninja đồng thời mang tới cho anh một mái ấm. Tuy nhiên, khi những bí mật từ quá khứ của Snake Eyes được bật mí, anh sẽ phải đối mặt với những thử thách lớn nhất trong cuộc đời.',
    popularity: 2186.173,
    poster_path: '/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg',
    release_date: '2021-07-22',
    title: 'Biệt Đội G.I. Joe: Xà Nhãn Báo Thù',
    video: false,
    vote_average: 6.9,
    vote_count: 649,
  },
  {
    adult: false,
    backdrop_path: '/hrzoy8vvUrxQixOM11pwW9AX7Bu.jpg',
    genre_ids: [80, 18],
    id: 524369,
    original_language: 'en',
    original_title: 'The Many Saints of Newark',
    overview: '',
    popularity: 1594.364,
    poster_path: '/1UkbPQspPbq1FPbFP4VV1ELCfSN.jpg',
    release_date: '2021-09-22',
    title: 'The Many Saints of Newark',
    video: false,
    vote_average: 6.7,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: '/dNQTwFmEj1b5SktT8oWGH5Cunlx.jpg',
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: 'en',
    original_title: 'Shang-Chi and the Legend of the Ten Rings',
    overview:
      'Phim "Shang-Chi và Huyền Thoại Thập Luân" của Marvel Studios có sự tham gia của Simu Liu  (Lưu Tư Mộ) trong vai Shang-Chi (Thượng Khí), người phải đối mặt với quá khứ ngỡ đã quên khi bị lôi kéo vào mạng lưới của tổ chức bí ẩn Thập Hoàn. Phim còn có sự tham gia của Lương Triều Vỹ trong vai Wenwu (Văn Vũ), Awkwafina trong vai Katy, bạn của Shang-Chi và Dương Tử Quỳnh trong vai Jiang Nan, cùng với Fala Chen (Trần Pháp Lạp), Meng\'er Zhang (Trương Mộng Nhi), Florian Munteanu và Ronny Chieng (Tiền Tính Y).',
    popularity: 1224.716,
    poster_path: '/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
    release_date: '2021-09-01',
    title: 'Shang-Chi và Huyền Thoại Thập Luân',
    video: false,
    vote_average: 7.8,
    vote_count: 1262,
  },
  {
    adult: false,
    backdrop_path: '/iDLtDgxLiYsarfdQ4msUhUqoNPp.jpg',
    genre_ids: [878],
    id: 725273,
    original_language: 'en',
    original_title: 'Solitary',
    overview: '',
    popularity: 998.205,
    poster_path: '/ApwmbrMlsuOay5rXQA4Kbz7qJAl.jpg',
    release_date: '2021-09-24',
    title: 'Solitary',
    video: false,
    vote_average: 6.6,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
    genre_ids: [28, 80, 53],
    id: 385128,
    original_language: 'en',
    original_title: 'F9',
    overview:
      'Quá Nhanh Quá Nguy Hiểm 9: Huyền Thoại Tốc Độ là một bộ phim hành động sắp ra mắt của Mỹ do Justin Lin đạo diễn và Daniel Casey viết kịch bản. Phần tiếp theo của The Fate of the Furious 2017, đây sẽ là phần thứ chín của mạch truyện chính trong loạt phim The Fast Saga và bộ phim dài thứ mười được phát hành tổng thể.',
    popularity: 950.675,
    poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
    release_date: '2021-05-19',
    title: 'Quá Nhanh Quá Nguy Hiểm 9: Huyền Thoại Tốc Độ',
    video: false,
    vote_average: 7.4,
    vote_count: 4059,
  },
  {
    adult: false,
    backdrop_path: '/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg',
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: 'en',
    original_title: 'The Boss Baby: Family Business',
    overview:
      'Nhóc trùm Ted giờ đây đã trở thành một triệu phú nổi tiếng trong khi Tim lại có một cuộc sống đơn giản bên vợ anh Carol và hai cô con gái nhỏ yêu dấu. Mỗi mùa Giáng sinh tới, cả Tina và Tabitha đều mong được gặp chú Ted nhưng dường như hai anh em nhà Templeton nay đã không còn gần gũi như xưa. Nhưng bất ngờ thay khi Ted lại có màn tái xuất không thể hoành tráng hơn khi đáp thẳng máy bay trực thăng tới nhà Tim trước sự ngỡ ngàng của cả gia đình.',
    popularity: 918.545,
    poster_path: '/uWStkK8bq9ixY3fc7y209ZleCoF.jpg',
    release_date: '2021-07-01',
    title: 'Nhóc Trùm P2: Nối Nghiệp Gia Đình',
    video: false,
    vote_average: 7.7,
    vote_count: 1506,
  },
  {
    adult: false,
    backdrop_path: '/7WJjFviFBffEJvkAms4uWwbcVUk.jpg',
    genre_ids: [12, 14, 35, 28],
    id: 451048,
    original_language: 'en',
    original_title: 'Jungle Cruise',
    overview:
      'Nội dung phim kể về một cặp đôi đi thám hiểm cùng nhau - Frank và Lily. Một người là thuyền trưởng người Mỹ và một người là nhà thám hiểm Anh quyết tâm hành trình vào rừng rậm Amazon để tìm kiếm một cây thần thoại với khả năng chữa bệnh đáng kinh ngạc.',
    popularity: 889.059,
    poster_path: '/vtuDGjaXvMhrNzFeLqanTiNPlK3.jpg',
    release_date: '2021-07-28',
    title: 'Jungle Cruise: Thám Hiểm Rừng Xanh',
    video: false,
    vote_average: 7.8,
    vote_count: 2939,
  },
];

export const populerList: Movie[] = [
  {
    adult: false,
    backdrop_path: '/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg',
    genre_ids: [878, 28],
    id: 580489,
    original_language: 'en',
    original_title: 'Venom: Let There Be Carnage',
    overview:
      'Siêu bom tấn #VENOM: LET THERE BE CARNAGE vừa bất ngờ tung đoạn trailer mãn nhãn, hứa hẹn trận chiến khốc liệt nhất giữa Venom và kẻ thù truyền kiếp, Carnage. Phim sẽ khởi chiếu DUY NHẤT TẠI RẠP vào ngày 24.09.2021 sắp tới. Cùng đón chờ!!',
    popularity: 9295.845,
    poster_path: '/489LD1LL2zQxFLbU6o5oslBhvwQ.jpg',
    release_date: '2021-09-30',
    title: 'Venom: Đối Mặt Tử Thù',
    video: false,
    vote_average: 7.2,
    vote_count: 627,
  },
  {
    adult: false,
    backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: 'en',
    original_title: 'Free Guy',
    overview:
      'Guy - Nhân viên giao dịch ngân hàng, phát hiện anh ấy thực chất là người chơi nền trong trò chơi điện tử thế giới mở. Guy quyết định trở thành người anh hùng và viết lại câu chuyện của chính mình. Giờ đây, trong một thế giới không còn giới hạn, anh ấy quyết định trở thành người giải cứu thế giới, theo cách của chính mình.',
    popularity: 4249.292,
    poster_path: '/kvTTnQ8C4RF0bZUAoYPD913NQx4.jpg',
    release_date: '2021-08-11',
    title: 'Giải Cứu Guy',
    video: false,
    vote_average: 7.8,
    vote_count: 2684,
  },
  {
    adult: false,
    backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
    genre_ids: [878, 28],
    id: 335983,
    original_language: 'en',
    original_title: 'Venom',
    overview:
      'Quái Vật Venom là một kẻ thù nguy hiểm và nặng ký của Người nhện trong loạt series của Marvel. Chàng phóng viên Eddie Brock (do Tom Hardy thủ vai) bí mật theo dõi âm mưu xấu xa của một tổ chức và đã không may mắn khi nhiễm phải loại cộng sinh trùng ngoài hành tinh (Symbiote) và từ đó đã không còn làm chủ bản thân về thể chất lẫn tinh thần. Điều này đã dần biến anh thành quái vật đen tối và nguy hiểm nhất chống lại người Nhện - Venom ...',
    popularity: 3096.416,
    poster_path: '/bURIWlkMbzT8RdpemzCmQECo2Uh.jpg',
    release_date: '2018-09-28',
    title: 'Quái Vật Venom',
    video: false,
    vote_average: 6.8,
    vote_count: 11722,
  },
  {
    adult: false,
    backdrop_path: '/kTOheVmqSBDIRGrQLv2SiSc89os.jpg',
    genre_ids: [16, 35, 10751],
    id: 639721,
    original_language: 'en',
    original_title: 'The Addams Family 2',
    overview:
      'Sự trở lại của The Addams Family 2 vào năm 2021 sẽ mang tới những điều “dị thường” không thể ngờ tới. Chỉ vừa kịp tuyên bố điều này, chú béo Fester đã ăn ngay phải một cú chơi khăm từ người em họ lông lá Itt. Rủ Itt đi câu cá nhưng lại câu phải đúng thuốc nổ. Cháy hết quần áo, cô cháu gái Wednesday đã “giúp khéo” chú mình bằng cách phun mực đen lên người. Không cần nhiều dẫn giải, khán giả có thể nhận ra giọng lồng tiếng quen thuộc của nữ diễn Chloë Grace Moretz trong vai cô con gái lớn Wednesday “khó ở” của nhà Addams.',
    popularity: 2290.454,
    poster_path: '/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg',
    release_date: '2021-10-01',
    title: 'Gia Đình Addams 2',
    video: false,
    vote_average: 7.6,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: '/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg',
    genre_ids: [28, 12],
    id: 568620,
    original_language: 'en',
    original_title: 'Snake Eyes: G.I. Joe Origins',
    overview:
      'Snake Eyes: G.I. Joe Origins theo chân Snake Eyes - một chiến binh cô độc, ngoan cường bất ngờ được kết nạp vào gia tộc Arashikage sau khi cứu mạng người thừa kế của họ. Khi đến Nhật Bản, Arashikage dạy Snake Eyes những chiêu thức cơ bản của một chiến binh ninja đồng thời mang tới cho anh một mái ấm. Tuy nhiên, khi những bí mật từ quá khứ của Snake Eyes được bật mí, anh sẽ phải đối mặt với những thử thách lớn nhất trong cuộc đời.',
    popularity: 2186.173,
    poster_path: '/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg',
    release_date: '2021-07-22',
    title: 'Biệt Đội G.I. Joe: Xà Nhãn Báo Thù',
    video: false,
    vote_average: 6.9,
    vote_count: 649,
  },
  {
    adult: false,
    backdrop_path: '/owraiceOKtSOa3t8sp3wA9K2Ox6.jpg',
    genre_ids: [16, 28, 12, 878],
    id: 703771,
    original_language: 'en',
    original_title: 'Deathstroke: Knights & Dragons - The Movie',
    overview:
      'Mười năm trước, Slade Wilson - hay còn gọi là siêu sát thủ được mệnh danh là Deathstroke - đã mắc phải một sai lầm bi thảm và vợ và con trai của hắn đã phải trả một cái giá khủng khiếp. Giờ đây, một thập kỷ sau, gia đình Wilson một lần nữa bị đe dọa bởi Jackal giết người và những kẻ khủng bố của H.IV.E. Deathstroke có thể chuộc lại tội lỗi trong quá khứ hay gia đình anh ta sẽ phải trả giá cuối cùng?',
    popularity: 1911.463,
    poster_path: '/vFIHbiy55smzi50RmF8LQjmpGcx.jpg',
    release_date: '2020-08-04',
    title: 'Siêu Sát Thủ Và Rồng',
    video: false,
    vote_average: 6.9,
    vote_count: 269,
  },
  {
    adult: false,
    backdrop_path: '/hrzoy8vvUrxQixOM11pwW9AX7Bu.jpg',
    genre_ids: [80, 18],
    id: 524369,
    original_language: 'en',
    original_title: 'The Many Saints of Newark',
    overview: '',
    popularity: 1594.364,
    poster_path: '/1UkbPQspPbq1FPbFP4VV1ELCfSN.jpg',
    release_date: '2021-09-22',
    title: 'The Many Saints of Newark',
    video: false,
    vote_average: 6.7,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: '/7h5WAPAcUzOWpp2jrwHBB48790j.jpg',
    genre_ids: [16, 28],
    id: 843241,
    original_language: 'ja',
    original_title: '劇場版 七つの大罪 光に呪われし者たち',
    overview: '',
    popularity: 1507.709,
    poster_path: '/gtiNyP9BoQmPzjeDhvofUtUxpJV.jpg',
    release_date: '2021-07-02',
    title: '劇場版 七つの大罪 光に呪われし者たち',
    video: false,
    vote_average: 8.4,
    vote_count: 163,
  },
  {
    adult: false,
    backdrop_path: '/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg',
    genre_ids: [80, 53],
    id: 637534,
    original_language: 'fr',
    original_title: 'BAC Nord',
    overview:
      'Một lữ đoàn cảnh sát làm việc tại các khu dân cư nguy hiểm phía bắc của Marseille, nơi mức độ tội phạm cao hơn bất kỳ nơi nào khác trên nước Pháp.',
    popularity: 1438.935,
    poster_path: '/r2NnRp4mi4G3e0x9zINQIcnGNd8.jpg',
    release_date: '2021-08-18',
    title: 'Thành Trì',
    video: false,
    vote_average: 7.7,
    vote_count: 419,
  },
  {
    adult: false,
    backdrop_path: '/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg',
    genre_ids: [14, 12, 35],
    id: 589754,
    original_language: 'ru',
    original_title: 'Последний богатырь: Корень зла',
    overview:
      'Hòa bình đã được thiết lập tại Belogorie sau khi cái ác bị đánh bại và Ivan đang tận hưởng sự nổi tiếng mà anh xứng đáng. Không chỉ có được sự tín nhiệm từ gia đình, bạn bè và những điều mới lạ từ thế giới hiện đại đã mang tới cho anh một cuộc sống thoải mái, Ivan còn may mắn sở hữu thanh gươm phép thuật giúp việc di chuyển giữa hai thế giới trở nên thuận tiện hơn. Song, sự trỗi dậy của một ác quỷ cổ đại đã đe dọa thế giới ma thuật, Ivan quyết định hợp tác với những người bạn cũ và đối thủ của mình để bắt đầu cuộc hành trình dài tới vùng không gian mới, nhằm tìm cách đánh bạn kẻ thù cũng như trả lại hòa bình cho Belogorie.',
    popularity: 1366.965,
    poster_path: '/21dFNftKvX9a3bbnQjAMIzXLPKS.jpg',
    release_date: '2021-01-01',
    title: 'Chiến Binh Cuối Cùng: Cội Nguồn Của Quỷ',
    video: false,
    vote_average: 7.1,
    vote_count: 49,
  },
  {
    adult: false,
    backdrop_path: '/umAoDwLZMBrYeCDfbJYFRMuXWAr.jpg',
    genre_ids: [878],
    id: 681887,
    original_language: 'en',
    original_title: 'Cosmic Sin',
    overview: '',
    popularity: 1285.857,
    poster_path: '/6Wm7P6y22UZA40QuPYHyWyJ6leI.jpg',
    release_date: '2021-03-12',
    title: 'Vũ Trụ Tội Lỗi',
    video: false,
    vote_average: 4.5,
    vote_count: 330,
  },
  {
    adult: false,
    backdrop_path: '/dNQTwFmEj1b5SktT8oWGH5Cunlx.jpg',
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: 'en',
    original_title: 'Shang-Chi and the Legend of the Ten Rings',
    overview:
      'Phim "Shang-Chi và Huyền Thoại Thập Luân" của Marvel Studios có sự tham gia của Simu Liu  (Lưu Tư Mộ) trong vai Shang-Chi (Thượng Khí), người phải đối mặt với quá khứ ngỡ đã quên khi bị lôi kéo vào mạng lưới của tổ chức bí ẩn Thập Hoàn. Phim còn có sự tham gia của Lương Triều Vỹ trong vai Wenwu (Văn Vũ), Awkwafina trong vai Katy, bạn của Shang-Chi và Dương Tử Quỳnh trong vai Jiang Nan, cùng với Fala Chen (Trần Pháp Lạp), Meng\'er Zhang (Trương Mộng Nhi), Florian Munteanu và Ronny Chieng (Tiền Tính Y).',
    popularity: 1224.716,
    poster_path: '/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
    release_date: '2021-09-01',
    title: 'Shang-Chi và Huyền Thoại Thập Luân',
    video: false,
    vote_average: 7.8,
    vote_count: 1262,
  },
  {
    adult: false,
    backdrop_path: '/5PQhNs4M3RxIqaNAdBI6mXlXyYh.jpg',
    genre_ids: [27, 14, 9648],
    id: 839436,
    original_language: 'en',
    original_title: 'Dragon Fury',
    overview: '',
    popularity: 1126.79,
    poster_path: '/6WcJ4cV2Y3gnTYp5zHu968TYmTJ.jpg',
    release_date: '2021-06-15',
    title: 'Dragon Fury',
    video: false,
    vote_average: 5.6,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: '/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg',
    genre_ids: [28, 12, 14],
    id: 436969,
    original_language: 'en',
    original_title: 'The Suicide Squad',
    overview:
      'Chính phủ gửi những siêu tội phạm nguy hiểm nhất trên thế giới - Bloodsport, Peacemaker, King Shark, Harley Quinn và những người khác - đến hòn đảo Corto Maltese xa xôi, đầy kẻ thù. Được trang bị vũ khí công nghệ cao, họ băng qua khu rừng rậm nguy hiểm trong một nhiệm vụ tìm kiếm và tiêu diệt, chỉ có Đại tá Rick Flag trên mặt đất để bắt họ hành xử.',
    popularity: 1095.016,
    poster_path: '/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg',
    release_date: '2021-07-28',
    title: 'Suicide Squad: Điệp Vụ Cảm Tử',
    video: false,
    vote_average: 7.8,
    vote_count: 4379,
  },
  {
    adult: false,
    backdrop_path: '/mDTrJbn2YEzYrBsdu7ITKh3ef69.jpg',
    genre_ids: [28, 35, 12],
    id: 772436,
    original_language: 'es',
    original_title: 'Matando Cabos 2, La Máscara del Máscara',
    overview: '',
    popularity: 1018.896,
    poster_path: '/ycKNJTFOLN5qRtA7uI2yk2cE3eU.jpg',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2, La Máscara del Máscara',
    video: false,
    vote_average: 7.5,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: '/iDLtDgxLiYsarfdQ4msUhUqoNPp.jpg',
    genre_ids: [878],
    id: 725273,
    original_language: 'en',
    original_title: 'Solitary',
    overview: '',
    popularity: 998.205,
    poster_path: '/ApwmbrMlsuOay5rXQA4Kbz7qJAl.jpg',
    release_date: '2021-09-24',
    title: 'Solitary',
    video: false,
    vote_average: 6.6,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
    genre_ids: [28, 80, 53],
    id: 385128,
    original_language: 'en',
    original_title: 'F9',
    overview:
      'Quá Nhanh Quá Nguy Hiểm 9: Huyền Thoại Tốc Độ là một bộ phim hành động sắp ra mắt của Mỹ do Justin Lin đạo diễn và Daniel Casey viết kịch bản. Phần tiếp theo của The Fate of the Furious 2017, đây sẽ là phần thứ chín của mạch truyện chính trong loạt phim The Fast Saga và bộ phim dài thứ mười được phát hành tổng thể.',
    popularity: 950.675,
    poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
    release_date: '2021-05-19',
    title: 'Quá Nhanh Quá Nguy Hiểm 9: Huyền Thoại Tốc Độ',
    video: false,
    vote_average: 7.4,
    vote_count: 4059,
  },
  {
    adult: false,
    backdrop_path: '/uRkRJjrxVa04w7k83Hy20FKot4G.jpg',
    genre_ids: [28],
    id: 859041,
    original_language: 'zh',
    original_title: '疯狂的拳头',
    overview: '',
    popularity: 857.616,
    poster_path: '/jeLePU48nWhPTKWSFMH2ni4o5bE.jpg',
    release_date: '2017-05-25',
    title: '疯狂的拳头',
    video: false,
    vote_average: 7.6,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: '/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg',
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: 'en',
    original_title: 'The Boss Baby: Family Business',
    overview:
      'Nhóc trùm Ted giờ đây đã trở thành một triệu phú nổi tiếng trong khi Tim lại có một cuộc sống đơn giản bên vợ anh Carol và hai cô con gái nhỏ yêu dấu. Mỗi mùa Giáng sinh tới, cả Tina và Tabitha đều mong được gặp chú Ted nhưng dường như hai anh em nhà Templeton nay đã không còn gần gũi như xưa. Nhưng bất ngờ thay khi Ted lại có màn tái xuất không thể hoành tráng hơn khi đáp thẳng máy bay trực thăng tới nhà Tim trước sự ngỡ ngàng của cả gia đình.',
    popularity: 918.545,
    poster_path: '/uWStkK8bq9ixY3fc7y209ZleCoF.jpg',
    release_date: '2021-07-01',
    title: 'Nhóc Trùm P2: Nối Nghiệp Gia Đình',
    video: false,
    vote_average: 7.7,
    vote_count: 1506,
  },
  {
    adult: false,
    backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
    genre_ids: [16, 28, 12, 14],
    id: 635302,
    original_language: 'ja',
    original_title: '劇場版「鬼滅の刃」無限列車編',
    overview:
      'Trên đường điều tra sự mất tích của các Kiếm Sĩ thuộc Đội Diệt Quỷ, Tanjiro và các đồng đội cùng Viêm Trụ Rengoku rơi vào Huyết Quỷ Thuật ảo mộng của Quỷ Hạ Huyền Enmu. Cả bọn phải hiệp lực để bảo toàn tính mạng cho 200 hành khách trên chuyến tàu Vô Tận. Nhờ sự hi sinh của Viêm Trụ Rengoku, Quỷ Hạ Huyền đã bị đánh bại và mọi người được sống sót',
    popularity: 896.362,
    poster_path: '/2MJz10b6ItzpKm3vb95S3X5Vcna.jpg',
    release_date: '2020-10-16',
    title: 'Thanh Gươm Diệt Quỷ: Chuyến Tàu Vô Tận',
    video: false,
    vote_average: 8.4,
    vote_count: 1736,
  },
];

export const upcommingList: Movie[] = [
  {
    adult: false,
    backdrop_path: '/kTOheVmqSBDIRGrQLv2SiSc89os.jpg',
    genre_ids: [16, 35, 10751],
    id: 639721,
    original_language: 'en',
    original_title: 'The Addams Family 2',
    overview:
      'Sự trở lại của The Addams Family 2 vào năm 2021 sẽ mang tới những điều “dị thường” không thể ngờ tới. Chỉ vừa kịp tuyên bố điều này, chú béo Fester đã ăn ngay phải một cú chơi khăm từ người em họ lông lá Itt. Rủ Itt đi câu cá nhưng lại câu phải đúng thuốc nổ. Cháy hết quần áo, cô cháu gái Wednesday đã “giúp khéo” chú mình bằng cách phun mực đen lên người. Không cần nhiều dẫn giải, khán giả có thể nhận ra giọng lồng tiếng quen thuộc của nữ diễn Chloë Grace Moretz trong vai cô con gái lớn Wednesday “khó ở” của nhà Addams.',
    popularity: 2290.454,
    poster_path: '/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg',
    release_date: '2021-10-01',
    title: 'Gia Đình Addams 2',
    video: false,
    vote_average: 7.6,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: '/hrzoy8vvUrxQixOM11pwW9AX7Bu.jpg',
    genre_ids: [80, 18],
    id: 524369,
    original_language: 'en',
    original_title: 'The Many Saints of Newark',
    overview: '',
    popularity: 1594.364,
    poster_path: '/1UkbPQspPbq1FPbFP4VV1ELCfSN.jpg',
    release_date: '2021-09-22',
    title: 'The Many Saints of Newark',
    video: false,
    vote_average: 6.7,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: '/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg',
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: 'en',
    original_title: 'The Boss Baby: Family Business',
    overview:
      'Nhóc trùm Ted giờ đây đã trở thành một triệu phú nổi tiếng trong khi Tim lại có một cuộc sống đơn giản bên vợ anh Carol và hai cô con gái nhỏ yêu dấu. Mỗi mùa Giáng sinh tới, cả Tina và Tabitha đều mong được gặp chú Ted nhưng dường như hai anh em nhà Templeton nay đã không còn gần gũi như xưa. Nhưng bất ngờ thay khi Ted lại có màn tái xuất không thể hoành tráng hơn khi đáp thẳng máy bay trực thăng tới nhà Tim trước sự ngỡ ngàng của cả gia đình.',
    popularity: 918.545,
    poster_path: '/uWStkK8bq9ixY3fc7y209ZleCoF.jpg',
    release_date: '2021-07-01',
    title: 'Nhóc Trùm P2: Nối Nghiệp Gia Đình',
    video: false,
    vote_average: 7.7,
    vote_count: 1506,
  },
  {
    adult: false,
    backdrop_path: '/kIG81E0H4CxuYIRgyNyD0z3KSlM.jpg',
    genre_ids: [27, 53],
    id: 610253,
    original_language: 'en',
    original_title: 'Halloween Kills',
    overview: '',
    popularity: 686.433,
    poster_path: '/ir9eyz1mtgsohjvo7UYtqUfFuES.jpg',
    release_date: '2021-10-14',
    title: 'Halloween Kills',
    video: false,
    vote_average: 6.4,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: '/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg',
    genre_ids: [10749, 18],
    id: 744275,
    original_language: 'en',
    original_title: 'After We Fell',
    overview: '',
    popularity: 678.621,
    poster_path: '/3WfvjNWr5k1Zzww81b3GWc8KQhb.jpg',
    release_date: '2021-09-01',
    title: 'After We Fell',
    video: false,
    vote_average: 8,
    vote_count: 347,
  },
  {
    adult: false,
    backdrop_path: '/u5Fp9GBy9W8fqkuGfLBuuoJf57Z.jpg',
    genre_ids: [12, 28, 53],
    id: 370172,
    original_language: 'en',
    original_title: 'No Time to Die',
    overview:
      'Phần 25 của bộ phim điệp viên huyền thoại 007 sẽ tiếp nối câu chuyện về James Bond cùng những pha hành động táo bạo và hoành tráng hơn bao giờ hết. Sau sự kiện đầy ám ảnh trong Spectre, Bond lui về ở ẩn tại đất nước Jamaica, sống một cuộc đời cô độc nhưng bình lặng. Bỗng một người bạn cũ từ CIA xuất hiện, cầu xin anh giúp đỡ. Bond bất đắc dĩ phải tái xuất, nhưng không hề biết mình sẽ đối đầu với thế lực nào. Chi tiết đáng chú ý nhất là chiếc mặt nạ trắng vỡ nửa, đánh dấu sự xuất hiện của tên ác nhân kì quái bậc nhất trong cả series 007. Màn chạm trán giữa Bond và kẻ thù nguy hiểm này sẽ vén màn những bí ẩn còn để ngỏ và tiếp theo đó, có thể là một cuộc đối đầu “sinh tử”.',
    popularity: 542.788,
    poster_path: '/6obsiTBb1D6Yc32q0BgAIFKOABu.jpg',
    release_date: '2021-09-29',
    title: 'Điệp Viên 007: Không Phải Lúc Chết',
    video: false,
    vote_average: 7.3,
    vote_count: 694,
  },
  {
    adult: false,
    backdrop_path: '/aknvFyJUQQoZFtmFnYzKi4vGv4J.jpg',
    genre_ids: [28, 12, 18, 878],
    id: 438631,
    original_language: 'en',
    original_title: 'Dune',
    overview:
      'Dune xoay quanh câu chuyện về Paul Atreides một chàng trai trẻ đầy tài năng và thông minh anh được sinh ra trong cuộc sống vô cùng tuyệt vời và vượt khỏi tầm hiểu biết của anh, không những thế anh còn phải du hành đến một hành tinh đầy nguy hiểm nhất trong vũ trụ để có thể bảo vệ an toàn cuộc sống trong tương lai của gia đình và người thân của anh. Nhưng những thế lực tàn ác đã trỗi dậy và gây xung đột về sự cung cấp tài nguyên cho sự tồn tại của hành tinh. Và chỉ có những người dũng cảm vượt qua được nỗi sợ hãi mới có thể giữ được mạng sống trên hành tinh này.',
    popularity: 459.903,
    poster_path: '/lr3cYNDlJcpT1EWzFH42aSIvkab.jpg',
    release_date: '2021-09-15',
    title: 'Dune: Hành tinh cát',
    video: false,
    vote_average: 8.1,
    vote_count: 1531,
  },
  {
    adult: false,
    backdrop_path: '/3pIqd1hgZ2xqzWEyiYp4blqE9Fi.jpg',
    genre_ids: [53, 36, 18],
    id: 522241,
    original_language: 'en',
    original_title: 'The Courier',
    overview:
      'The Courier (2020) thuộc thể loại chiến tranh, hành động với sự góp mặt của Benedict Cumberbatch, Merab Ninidze, Rachel Brosnahan do Dominic Cooke làm đạo diễn. Thời lượng 1h 52mn, nội dung xoay quanh công việc của Greville Wynne một điệp viên Chiến tranh Lạnh, đang cố gắng thực hiện đưa những nguồn tin về Nga để nhanh chóng chấm dứt Khủng hoảng tên lửa Cuba. ...',
    popularity: 363.05,
    poster_path: '/zFIjKtZrzhmc7HecdFXXjsLR2Ig.jpg',
    release_date: '2021-03-18',
    title: 'Người Đưa Tin',
    video: false,
    vote_average: 7.1,
    vote_count: 423,
  },
  {
    adult: false,
    backdrop_path: '/sqmGvNabWUD2hlhEqejksr6HVeX.jpg',
    genre_ids: [18, 36],
    id: 617653,
    original_language: 'en',
    original_title: 'The Last Duel',
    overview: '',
    popularity: 229.981,
    poster_path: '/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg',
    release_date: '2021-10-13',
    title: 'The Last Duel',
    video: false,
    vote_average: 7.9,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: '/3G6wET9eLvYn3aoIj8NfQFhpYEB.jpg',
    genre_ids: [878, 28, 12, 18],
    id: 524434,
    original_language: 'en',
    original_title: 'Eternals',
    overview:
      'Chủng Tộc Bất Tử (The Eternals) là một nhóm gồm những người ngoài hành tinh cổ đại đã sống bí mật trên Trái đất trong hàng nghìn năm. Khi một bi kịch bất ngờ ập đến buộc họ phải thoát ra khỏi bóng tối, họ buộc phải đoàn tụ chống lại kẻ thù truyền kiếp nhất của nhân loại, Deviants.',
    popularity: 191.774,
    poster_path: '/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg',
    release_date: '2021-11-03',
    title: 'Chủng Tộc Bất Tử',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/99OiyEOsFecBiS5XkhQAB98rlP6.jpg',
    genre_ids: [16, 878, 10751, 35],
    id: 482321,
    original_language: 'en',
    original_title: "Ron's Gone Wrong",
    overview: '',
    popularity: 154.908,
    poster_path: '/gA9QxSravC2EVEkEKgyEmDrfL0e.jpg',
    release_date: '2021-10-15',
    title: "Ron's Gone Wrong",
    video: false,
    vote_average: 3.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/2nU5H8XIgtMkJrxsryP6nJuAHQ.jpg',
    genre_ids: [16, 18, 12, 10751],
    id: 805051,
    original_language: 'en',
    original_title: 'Smelliville',
    overview: '',
    popularity: 149.314,
    poster_path: '/w7PJ7fBEYOuaAMKfYa4zmw45v3N.jpg',
    release_date: '2021-01-01',
    title: 'Smelliville',
    video: false,
    vote_average: 7.5,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: '/2RHjd10wqv57xYzZkNK8Sl09Ddt.jpg',
    genre_ids: [16, 28, 35, 14, 12],
    id: 768744,
    original_language: 'ja',
    original_title:
      '僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション',
    overview: '',
    popularity: 130.892,
    poster_path: '/yjdOpEtlzlAnw4Kw0NGw25VrbIb.jpg',
    release_date: '2021-08-06',
    title: '僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション',
    video: false,
    vote_average: 7.4,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: '/g6wufgtycJCP508tlC3crSYFCgC.jpg',
    genre_ids: [37, 18],
    id: 749274,
    original_language: 'en',
    original_title: 'Cry Macho',
    overview: '',
    popularity: 98.299,
    poster_path: '/wqaaWAlXgLNGdAemU7wNvFZ70hr.jpg',
    release_date: '2021-09-16',
    title: 'Cry Macho',
    video: false,
    vote_average: 6.8,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: '/4Tz8V8aRim8cFgKEWprSUjBy8tY.jpg',
    genre_ids: [18, 10402, 10749],
    id: 776503,
    original_language: 'en',
    original_title: 'CODA',
    overview:
      'CODA (child of deaf adults), Ruby là người duy nhất vẫn có thể nghe trong một gia đình khiếm thính. Khi phát hiện ra niềm đam mê ca hát, Ruby phải lựa chọn giữa nghĩa vụ gia đình và ước mơ bản thân.',
    popularity: 80.317,
    poster_path: '/BzVjmm8l23rPsijLiNLUzuQtyd.jpg',
    release_date: '2021-07-30',
    title: 'Giai Điệu Con Tim',
    video: false,
    vote_average: 8.3,
    vote_count: 228,
  },
  {
    adult: false,
    backdrop_path: '/nVeKN24TscMhQKBuGGYc2ovFBO5.jpg',
    genre_ids: [35, 10751],
    id: 763873,
    original_language: 'en',
    original_title: 'Under Wraps',
    overview: '',
    popularity: 66.611,
    poster_path: '/2EnHRyHdboUWz120LDiAk2M2Lgc.jpg',
    release_date: '2021-10-30',
    title: 'Under Wraps',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/JFqL21ZaKWqneuk1wzmAIEWg8I.jpg',
    genre_ids: [18],
    id: 567690,
    original_language: 'en',
    original_title: 'Dear Evan Hansen',
    overview: '',
    popularity: 57.462,
    poster_path: '/83pobg0tx4r4JeLenCAemanpnS2.jpg',
    release_date: '2021-09-24',
    title: 'Dear Evan Hansen',
    video: false,
    vote_average: 6.6,
    vote_count: 42,
  },
  {
    adult: false,
    backdrop_path: '/kXB7UhPxNP7AwfArqPqcCr7bw5L.jpg',
    genre_ids: [27, 9648, 18],
    id: 516329,
    original_language: 'en',
    original_title: 'Antlers',
    overview: '',
    popularity: 40.428,
    poster_path: '/klsDRXM68wV7vZTTaAOuu62VNA1.jpg',
    release_date: '2021-10-28',
    title: 'Antlers',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/1yqVaDR7uIA3Xx9GQIhbEbh5pEe.jpg',
    genre_ids: [9648, 53, 80, 35, 18],
    id: 571648,
    original_language: 'ko',
    original_title: '지푸라기라도 잡고 싶은 짐승들',
    overview:
      'Nội dung phim xoay quanh nhân vật Joong-Man, một người đàn ông thất bại trong kinh doanh và đang phải làm việc bán thời gian tại một phòng tắm hơi. Câu chuyện bắt đầu từ khi anh nhặt được một túi tiền và quyết định lấy nó.Thực ra, số tiền này thuộc về người phụ nữ mới bị giết hại tên Yeon-Hee, cô vừa mới được người bạn trai Tae-Young cho mượn để giải quyết công việc. Tuy nhiên, Tae-Young lại vay khoản tiền lớn này từ ông trùm khét tiếng, vì anh là một nhân viên hải quan nên mới được tin tưởng như vậy. Nhưng hiện tại, tiền không còn, người đã mất, Tae-Young chính là mục tiêu đòi nợ của bọn cho vay và liên tục phải đối mặt với những áp lực khủng khiếp. Mọi chuyện rồi sẽ ra sao, ai mới là kẻ chiến thắng cuối cùng trong cuộc chiến rắc rối này.',
    popularity: 37.082,
    poster_path: '/qflrq8UvC2YE4lhudU6voXliwyc.jpg',
    release_date: '2020-02-19',
    title: 'Chó Săn Tiền',
    video: false,
    vote_average: 7.2,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: '/r7dJqfmspzVlHYWXBiKn7NP8ZBw.jpg',
    genre_ids: [18, 53, 80],
    id: 643532,
    original_language: 'en',
    original_title: 'The Card Counter',
    overview: '',
    popularity: 35.084,
    poster_path: '/y5DNLVg0gPiGSkuK4yFc4fjQ42Q.jpg',
    release_date: '2021-09-03',
    title: 'The Card Counter',
    video: false,
    vote_average: 6.5,
    vote_count: 145,
  },
];

export const popularTVList: TV[] = [
  {
    backdrop_path: '/n00M5kO1C9xBkusfe56Zvrihw6c.jpg',
    first_air_date: '2021-09-17',
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: 'Trò Chơi Con Mực - Squid Game',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '오징어 게임',
    overview:
      'Squid Game – Trò Chơi Con Mực (tên tiếng Hàn 오징어 게임) là một series Hàn Quốc trên Netflix được lấy cảm hứng từ một trò chơi quen thuộc dành cho trẻ em ở Hàn Quốc ngày xưa. Vào những năm 1980, đây là một trong những trò giải trí phổ biến thường được chơi trên khoảng sân trống với những hình thù được vẽ trên đất.  Squid Game – Trò Chơi Con Mực (tên tiếng Hàn 오징어 게임) là một series Hàn Quốc trên Netflix được lấy cảm hứng từ một trò chơi quen thuộc dành cho trẻ em ở Hàn Quốc ngày xưa. Vào những năm 1980, đây là một trong những trò giải trí phổ biến thường được chơi trên khoảng sân trống với những hình thù được vẽ trên đất.',
    popularity: 6805.409,
    poster_path: '/yACIAqAkSLkX4coHafpyLWAtQjw.jpg',
    vote_average: 7.9,
    vote_count: 7510,
  },
  {
    backdrop_path: '/bxU79lpl8ZQAVJ72155kqWkuqMu.jpg',
    first_air_date: '2019-01-11',
    genre_ids: [35, 18],
    id: 81356,
    name: 'Giáo Dục Giới Tính',
    origin_country: ['GB'],
    original_language: 'en',
    original_name: 'Sex Education',
    overview:
      'Cậu chàng Otis nhút nhát, hưởng xái từ bà mẹ chuyên gia, khá rành rọt về mấy chuyện "ấy ấy". Thế là cô bạn nổi loạn Maeve bèn rủ cậu mở phòng khám tư vấn cho chúng bạn.',
    popularity: 1408.878,
    poster_path: '/DyKOkHR8zjh7Ry1yvTQt8D3YrD.jpg',
    vote_average: 8.4,
    vote_count: 4909,
  },
  {
    backdrop_path: '/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg',
    first_air_date: '2016-01-25',
    genre_ids: [80, 10765],
    id: 63174,
    name: 'Chúa Tể Địa Ngục',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Lucifer',
    overview:
      'Chán nản và không hạnh phúc với tư cách là Chúa tể Địa ngục, Lucifer Morningstar từ bỏ ngai vàng của mình và trở về Los Angeles, nơi anh hợp tác với thám tử LAPD Chloe Decker để tiêu diệt bọn tội phạm. Nhưng càng rời xa thế giới ngầm, mối đe dọa mà kẻ tồi tệ nhất của loài người có thể thoát ra càng lớn.',
    popularity: 1270.852,
    poster_path: '/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg',
    vote_average: 8.5,
    vote_count: 10735,
  },
  {
    backdrop_path: '/4N6zEMfZ57zNEQcM8gWeERFupMv.jpg',
    first_air_date: '2021-08-11',
    genre_ids: [16, 10759, 10765],
    id: 91363,
    name: 'What If...?',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'What If...?',
    overview:
      'What If...? là sê-ri phim truyền hình Mỹ, phát sóng trên nền tảng xem phim trực tuyến Disney+. Giám chế phim là A.C. Bradley, cùng với đạo diễn là Bryan Andrews. Tác phẩm được xây dựng trong bối cảnh của Vũ trụ Điện ảnh Marvel (MCU), nói về những biến cố có thể xảy ra nếu các sự kiện trong các phim điện ảnh của vũ trụ này không đi theo chiều hướng ban đầu.',
    popularity: 1123.605,
    poster_path: '/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg',
    vote_average: 8.5,
    vote_count: 2326,
  },
  {
    backdrop_path: '/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg',
    first_air_date: '2010-10-31',
    genre_ids: [10759, 18, 10765],
    id: 1402,
    name: 'Xác Sống',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Walking Dead',
    overview:
      'Loạt phim xoay quanh nhân vật do nam diễn viên Andrew Lincoln thủ vai chính là phó cảnh sát trưởng Rick Grimes, người đã tỉnh dậy sau một khoảng thời gian hôn mê và nhận ra rằng thế giới đã bước vào thời kỳ hậu tận thế với sự xuất hiện tràn lan của thây ma ăn thịt. Anh lên đường tìm kiếm gia đình mình và gặp được nhiều người vẫn còn sống sót trên đường đi.',
    popularity: 964.636,
    poster_path: '/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg',
    vote_average: 8.1,
    vote_count: 11841,
  },
  {
    backdrop_path: '/9OYu6oDLIidSOocW3JTGtd2Oyqy.jpg',
    first_air_date: '2017-09-25',
    genre_ids: [18],
    id: 71712,
    name: 'Bác Sĩ Thiên Tài',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Good Doctor',
    overview:
      'Một bác sĩ trẻ mắc hội chứng bác học được nhận vào khoa phẫu thuật tim của một bệnh viện danh tiếng. Liệu một người bị tự kỷ có thể cứu người? Phim dựa trên series cùng tên của Hàn Quốc.',
    popularity: 948.708,
    poster_path: '/z1K4mJwISETia59rrnMdXxzoSrZ.jpg',
    vote_average: 8.6,
    vote_count: 9566,
  },
  {
    backdrop_path: '/yv5oliNUwu82JT1XUbz1WSKm18E.jpg',
    first_air_date: '2021-10-01',
    genre_ids: [18],
    id: 111141,
    name: 'Nghề Giúp Việc - Maid',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Maid',
    overview:
      'Sau khi trốn khỏi mối quan hệ bạo hành, bà mẹ trẻ tìm được công việc dọn dẹp. Cô nỗ lực chu cấp cho con và mang đến cho hai mẹ con một tương lai tốt đẹp hơn.',
    popularity: 979.071,
    poster_path: '/4brWcSXdH31BZUTtRTHj2BYFe6M.jpg',
    vote_average: 7.4,
    vote_count: 48,
  },
  {
    backdrop_path: '/5teVRNsc6uDIIYHlAssrsxtUc5e.jpg',
    first_air_date: '2014-10-07',
    genre_ids: [18, 10765],
    id: 60735,
    name: 'Tia Chớp',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Flash',
    overview:
      'Phim dựa theo một nhân vật của DC Comics, trong 1 thí nghiệm tại Starling City, anh chàng Barry đã vô tình bị ảnh hưởng bởi vụ nổ trong thí nghiệm khiến anh hôm mê bất tỉnh nhiều ngày trong bệnh viện. Khi tỉnh dậy, anh ta đã phát hiện ra rằng mình có khả năng đặc biệt đó là tăng tốc độ cơ thể và di chuyển siêu nhanh. Kể từ đây, huyền thoại về người anh hùng Flash bắt đầu.',
    popularity: 774.9,
    poster_path: '/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg',
    vote_average: 7.8,
    vote_count: 8569,
  },
  {
    backdrop_path: '/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg',
    first_air_date: '2017-05-02',
    genre_ids: [80, 18],
    id: 71446,
    name: 'Phi Vụ Triệu Đô',
    origin_country: ['ES'],
    original_language: 'es',
    original_name: 'La Casa de Papel',
    overview:
      'Tám tên cướp khống chế các con tin trong Xưởng in tiền Hoàng gia Tây Ban Nha trong khi kẻ chủ mưu thao túng cảnh sát để thực hiện kế hoạch của hắn.',
    popularity: 713.346,
    poster_path: '/z01Dc0Ly2GmCpLe6Scx4d3dPP1S.jpg',
    vote_average: 8.3,
    vote_count: 14723,
  },
  {
    backdrop_path: '/pG4hoMaHaiAFRMDKsKbBbWTyAma.jpg',
    first_air_date: '2018-09-09',
    genre_ids: [9648, 80, 18],
    id: 78191,
    name: 'Kẻ Đeo Bám',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'You',
    overview:
      'Tựa như liều thuốc độc khó cưỡng, lại ôm mối cuồng si mãnh liệt, anh dùng đến cả những biện pháp cực đoan để len lỏi vào cuộc sống của những cô gái mình mê đắm.',
    popularity: 624.259,
    poster_path: '/yxIdKGEjagaLs5kMjw92kAHmopH.jpg',
    vote_average: 8.1,
    vote_count: 1345,
  },
];
